### ISSUE TITLE
!ttt <user> causing problem

### ISSUE THREAD

**Issue by WideIrenaKan2** [utarwyn/discord-tictactoe#17]
When I do !ttt {user} I get this error, this happens only when I mention them:

]: DiscordAPIError: Cannot send an empty message
     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
     at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:97:5) {
 method: 'post',
  path: '/channels/775272137673408532/messages',
  code: 50006,
   httpStatus: 400
: }

I tried mentioning them by using ID, username, username and tag but its says "You could not challenge {user}. Please mention another user."

But when I do !ttt only it works very great

**Comment by WideIrenaKan2** [comment]
Issue resolved on Discord!
