### ISSUE TITLE
Cant start Duel

### ISSUE THREAD

**Issue by Tman0560** [utarwyn/discord-tictactoe#18]
I can't seem to get a duel to start. I can play against the AI but when I use !ttt and then the users @ nothing works. Could anyone help me out?

**Comment by anjannair** [comment]
@Tman0560 have you followed steps mentioned in `README`?

**Comment by Tman0560** [comment]
Yes I have. I used the “use it as a independent bot” instructions in the Read Me

**Comment by anjannair** [comment]
@Tman0560 no console errors? Bot token is valid?

**Comment by Tman0560** [comment]
No console errors. Bot Token is Valid. The bot works against the AI but it does nothing when doing !ttt @user. I wrote the script in Visual Studio Code.

**Comment by anjannair** [comment]
@Tman0560 attack a screenshot of the code if possible? So I can have look at it

**Comment by Tman0560** [comment]
![main js - Discord Bot - Visual Studio Code 12_16_2020 12_04_45 PM](https://user-images.githubusercontent.com/75875119/102400766-3bc04500-3f97-11eb-8102-2ec23128b70c.png)
![main js - Discord Bot - Visual Studio Code 12_16_2020 12_04_32 PM](https://user-images.githubusercontent.com/75875119/102400770-3d8a0880-3f97-11eb-891a-29b0af95ade9.png)
![main js - Discord Bot - Visual Studio Code 12_16_2020 12_04_28 PM](https://user-images.githubusercontent.com/75875119/102400775-3ebb3580-3f97-11eb-9225-0fd08b5a5b74.png)
![main js - Discord Bot - Visual Studio Code 12_16_2020 12_04_21 PM](https://user-images.githubusercontent.com/75875119/102400778-3fec6280-3f97-11eb-8491-1e88c9f772b9.png)

Sure

**Comment by utarwyn** [comment]
Hello @Tman0560, which version of Node do you use? I will try to reproduce the bug to fix it. Sounds weird because you should have either an error message in your text channel or a fatal error with the stack trace in your console. Also, the mentionned member must validate those conditions to start a duel with it :
https://github.com/utarwyn/discord-tictactoe/blob/37f936092bfa37801b52cb9c4b40322c40701175/src/bot/commands/StartCommand.ts#L67-L70

Otherwise a warning message is sent by the bot in the same channel, do you see it? The only case when no message is either printed in the console or text channel is when the command is not handled or a game is already running in it. Or a permission problem.

**Comment by Tman0560** [comment]
I use Node version 15.4, Also I use a raspberry pi 3 to run the bot. It’s a 32 bit system so do you think that affects it?

**Comment by Tman0560** [comment]
@utarwyn @anjannair With some messing around I managed to have it give me an error code. Here's the error code...

/usr/bin/node ./main.js
null: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at DuelRequestMessage.<anonymous> (/home/pi/Desktop/discordbot/node_modules/discord-tictactoe/dist/src/bot/channel/DuelRequestMessage.js:25:55)
    at Generator.next (<anonymous>)
    at /home/pi/Desktop/discordbot/node_modules/discord-tictactoe/dist/src/bot/channel/DuelRequestMessage.js:8:71 {stack: 'TypeError: fields.flat is not a function
    …st/src/bot/channel/DuelRequestMessage.js:8:71', message: 'fields.flat is not a function'}
arg0: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at DuelRequestMessage.<anonymous> (/home/pi/Desktop/discordbot/node_modules/discord-tictactoe/dist/src/bot/channel/DuelRequestMessage.js:25:55)
    at Generator.next (<anonymous>)
    at /home/pi/Desktop/discordbot/node_modules/discord-tictactoe/dist/src/bot/channel/DuelRequestMessage.js:8:71 {stack: 'TypeError: fields.flat is not a function
    …st/src/bot/channel/DuelRequestMessage.js:8:71', message: 'fields.flat is not a function'}
: _tickCallback @ internal/process/next_tick.js:68:7
null: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/home/pi/Desktop/discordbot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at DuelRequestMessage.<anonymous> (/home/pi/Desktop/discordbot/node_modules/discord-tictactoe/dist/src/bot/channel/DuelRequestMessage.js:25:55)
    at Generator.next (<anonymous>)
    at /home/pi/Desktop/discordbot/node_modules/discord-tictactoe/dist/src/bot/channel/DuelRequestMessage.js:8:71 {stack: 'TypeError: fields.flat is not a function
    …st/src/bot/channel/DuelRequestMessage.js:8:71', message: 'fields.flat is not a function'}

**Comment by utarwyn** [comment]
Oh.. it seems to be a `Discord.js` problem. Like that issue on their repository: discordjs/discord.js#3913
They are all saying to upgrade Node to at least v12+ or v14+. So check your node version with `node -version` and upgrade it if needed. This is not a problem with my bot I think.

**Comment by Tman0560** [comment]
Okay cool I will do some investigating then on that I will let you know if it was the node version

**Comment by Tman0560** [comment]
It was the node version and nothing wrong with your bot. Thank you so much for your help!

**Comment by utarwyn** [comment]
Great news! Thank you for the feedback, enjoy the bot :smile:
