### ISSUE TITLE
"ReactionManager.removeAll" error but I configured the system with buttons

### ISSUE THREAD

**Issue by ravenastar-js** [utarwyn/discord-tictactoe#442]
**Describe the bug**
● The error occurs when the bot doesn't have the "manage messages" permission.
● the system has been configured to respond with Buttons instead of reactions.

**To Reproduce**
![](https://i.imgur.com/WpsdLII.gif)

**Script used**
```js
const TicTacToe = require('discord-tictactoe')
const game = new TicTacToe({ language: "pt-br", commandOptionName: "player2", embedColor: "#00a859", gameBoardDisableButtons: true })
game.handleInteraction(interaction)
 ```

**Code error**
```js
DiscordAPIError: Missing Permissions
    at RequestHandler.execute (D:\db\staralienbeta-v13\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\db\staralienbeta-v13\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async ReactionManager.removeAll (D:\db\staralienbeta-v13\node_modules\discord.js\src\managers\ReactionManager.js:61:5) {
  method: 'delete',
  path: '/channels/1076646065463382066/messages/1076670057268138129/reactions',
  code: 50013,
  httpStatus: 403,
  requestData: { json: undefined, files: [] }
} Promise {
  <rejected> DiscordAPIError: Missing Permissions
      at RequestHandler.execute (D:\db\staralienbeta-v13\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (D:\db\staralienbeta-v13\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
      at async ReactionManager.removeAll (D:\db\staralienbeta-v13\node_modules\discord.js\src\managers\ReactionManager.js:61:5) {
    method: 'delete',
    path: '/channels/1076646065463382066/messages/1076670057268138129/reactions',
    code: 50013,
    httpStatus: 403,
    requestData: { json: undefined, files: [] }
  }
}
```

**discord-tictactoe version:**
```
NPM package ➤ discord-tictactoe@^3
discord.js ➤ v13.*
node.js ➤ v16.17.0
Module version ➤ v3.*
```

**Additional context**
the error "ReactionManager.removeAll" should not occur because the system is by buttons

**Comment by utarwyn** [comment]
Thank you for the feedback! I also have to remove permission "ADD_REACTIONS" from needed list if reactions are disabled
