### ISSUE TITLE
DiscordAPIError: Cannot send an empty message (node v14.15.2)

### ISSUE THREAD

**Issue by Toskan4134** [utarwyn/discord-tictactoe#45]
I can't update node's version and each time I try to use the Player vs Player command it sends this
```error
DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/rbd/pnpm-volume/04410727-134b-45fc-bd85-405c5d9cfcc1/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/rbd/pnpm-volume/04410727-134b-45fc-bd85-405c5d9cfcc1/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/807041758205837312/messages',
  code: 50006,
  httpStatus: 400
}
```
What can I do to solve this? I'm actually using Glitch.

**Comment by utarwyn** [comment]
Hello @Toskan4134, I think that you got the same problem as in issue #41 ?
A fix has been made but not released yet. You can modify source code for now if you want an hotfix.

**Comment by utarwyn** [comment]
I have checked what is Glitch and I understand that you cannot do the trick explained in the mentionned issue.
I think the only way for you to use the module is to wait for a new release, I hope really soon!

**Comment by Toskan4134** [comment]
Thanks
